### ISSUE TITLE
Ambiguous serialization for `()?`

### ISSUE THREAD

**Issue by hvenev** [varlink/documentation#1]
As `()` is a fixed-size type, both possible values of the type `()?` are stored the same way - as the empty bytearray.

Idea: append a 0 byte to the end of a nullable iff the empty bytestring is a valid value of the underlying type. For example, `(a: int8, b: int32[])` and `string` don't need an extra 0 byte, but `()` and `int32[0]` do.

**Comment by larskarlitski** [comment]
> As `()` is a fixed-size type, both possible values of the type `()?` are stored the same way - as the empty bytearray.

No, `()` is serialized as a single 0 byte, whereas `()?` is serialized 0 bytes in the `null` case.

We're appending a single 0 byte to all values that have a nullable variable-sized type.

Thanks for your interest! Sorry that the documentation is still pretty sparse at the moment.
