### ISSUE TITLE
Why invent a language?

### ISSUE THREAD

**Issue by rektide** [varlink/documentation#2]
So, it's great that varlink the protocol uses bog-standard JSON to talk. That will greatly speed developers abilities to write tools.

I'm curious though, why invent a new language for the definitions? That, to me, seems like it will slow down development of tooling around the definitions, versus, say, having interface definitions be defined also in JavaScript. What are the pro's and con's that pushed varlink found that pushed towards creating a brand new language?

Off the top of my head, the first super obvious issue with JSON is a lack of comments. I've seen two approaches to this:
a) use json5.org which does allow comments,
b) the double-variable style comments:

```
{
  "method": "this method tells us to go to the next element",
  "method": "advanceElement",
  "arguments": [{
    "name": "this argument tells us how many next elements to advance",
    "name": "count"
  }]
}
```

It hurts me a good bit to think that the world needs YET ANOTHER interface definition language. There are so so so so so so so so many already. And every time, it's a huge slow down implementing the interface definition language whenever the world wants to bring a protocol to a new language. It's great that the protocol is JSON, but I'd love it if the interface-definition could also re-use some existing language (yaml would be fine, allows comments, or webidl, protobuf idl, relax-ng, json-ld schema, thrift idl,...) rather than create something new out of nothing.

**Comment by haraldh** [comment]
We invented the language, because it is the center of varlink. Creating, reading and discussing varlink files requires a human readable language.
